
from tkinter import *
import os
from mrrLinksdefinition import action_0, action_1, action_2, OpenLink

root = Tk()
root.title("Fast Action Pallete for product Engineer")

def open_MRR():
    top_mrr = Toplevel()
    top_mrr.title("MRR Windows Environment ")
    
    Label_Links = Label(top_mrr, text="Links", pady=30, padx=80)
    Label_Links.grid(row=0,column=1)
    
    Label_Apps = Label(top_mrr, text="Applications", pady=30, padx=80)
    Label_Apps.grid(row=0,column=2)

    Label_Env = Label(top_mrr, text="Enviroment", pady=30, padx=80)
    Label_Env.grid(row=0,column=3)

    Link0_Buttom = Button(top_mrr, text="MFQ2", pady=30, padx= 80, command=OpenLink())
    Link1_Buttom = Button(top_mrr, text="Q Incidents", pady=30, padx= 80, command=action_1)
    Link2_Buttom = Button(top_mrr, text="Q Events", pady=30, padx= 80, command=action_2)
    Link3_Buttom = Button(top_mrr, text="Failure Analysis", pady=30, padx= 80, command=action_1)
    Link4_Buttom = Button(top_mrr, text="CLiberacion", pady=30, padx= 80, command=action_1)
    Link5_Buttom = Button(top_mrr, text="PQA", pady=30, padx= 80, command=action_1)
    Link6_Buttom = Button(top_mrr, text="Prod Validation", pady=30, padx= 80, command=action_1)
    Link7_Buttom = Button(top_mrr, text="Concesion", pady=30, padx= 80, command=action_1)
    Link8_Buttom = Button(top_mrr, text="QI", pady=30, padx= 80, command=action_1)
    Link9_Buttom = Button(top_mrr, text="PQI", pady=30, padx= 80, command=action_1)

    App0_Buttom = Button(top_mrr, text="BTDB", pady=30, padx= 80, command=action_1)
    App1_Buttom = Button(top_mrr, text="SAP", pady=30, padx= 80, command=action_1)
    App2_Buttom = Button(top_mrr, text="ECAM", pady=30, padx= 80, command=action_1)
    App3_Buttom = Button(top_mrr, text="Actividades", pady=30, padx= 80, command=action_1)
    App4_Buttom = Button(top_mrr, text="ProdEngWeb", pady=30, padx= 80, command=action_1)
    App5_Buttom = Button(top_mrr, text="MWS", pady=30, padx= 80, command=action_1)
    App6_Buttom = Button(top_mrr, text="Oisnet", pady=30, padx= 80, command=action_1)
    App7_Buttom = Button(top_mrr, text="App7", pady=30, padx= 80, command=action_1)
    App8_Buttom = Button(top_mrr, text="App8", pady=30, padx= 80, command=action_1)
    App9_Buttom = Button(top_mrr, text="App9", pady=30, padx= 80, command=action_1)

    Env0_Buttom = Button(top_mrr, text="PQA_QAM", pady=30, padx= 80, command=action_1)
    Env1_Buttom = Button(top_mrr, text="QISupport", pady=30, padx= 80, command=action_1)
    Env2_Buttom = Button(top_mrr, text="MiniPSS", pady=30, padx= 80, command=action_1)
    Env3_Buttom = Button(top_mrr, text="DLR", pady=30, padx= 80, command=action_1)
    Env4_Buttom = Button(top_mrr, text="CheckList", pady=30, padx= 80, command=action_1)
    Env5_Buttom = Button(top_mrr, text="ReportesAnalisis", pady=30, padx= 80, command=action_1)
    Env6_Buttom = Button(top_mrr, text="AnalisisWeb", pady=30, padx= 80, command=action_1)
    Env7_Buttom = Button(top_mrr, text="Mantenimientos", pady=30, padx= 80, command=action_1)
    Env8_Buttom = Button(top_mrr, text="App9", pady=30, padx= 80, command=action_1)
    Env9_Buttom = Button(top_mrr, text="App9", pady=30, padx= 80, command=action_1)


    # align buttoms in columns and rows according layout
    Link0_Buttom.grid(row=1,column=1)
    Link1_Buttom.grid(row=2,column=1)
    Link2_Buttom.grid(row=3,column=1)
    Link3_Buttom.grid(row=4,column=1)
    Link4_Buttom.grid(row=5,column=1)
    Link5_Buttom.grid(row=6,column=1)
    Link6_Buttom.grid(row=7,column=1)
    Link7_Buttom.grid(row=8,column=1)
    Link8_Buttom.grid(row=9,column=1)
    Link9_Buttom.grid(row=10,column=1)

    App0_Buttom.grid(row=1, column=2)
    App1_Buttom.grid(row=2, column=2)
    App2_Buttom.grid(row=3, column=2)
    App3_Buttom.grid(row=4, column=2)
    App4_Buttom.grid(row=5, column=2)
    App5_Buttom.grid(row=6, column=2)
    App6_Buttom.grid(row=7, column=2)
    App7_Buttom.grid(row=8, column=2)
    App8_Buttom.grid(row=9, column=2)
    App9_Buttom.grid(row=10, column=2)

    Env0_Buttom.grid(row=1, column=3)
    Env1_Buttom.grid(row=2, column=3)
    Env2_Buttom.grid(row=3, column=3)
    Env3_Buttom.grid(row=4, column=3)
    Env4_Buttom.grid(row=5, column=3)
    Env5_Buttom.grid(row=6, column=3)
    Env6_Buttom.grid(row=7, column=3)
    Env7_Buttom.grid(row=8, column=3)
    Env8_Buttom.grid(row=9, column=3)
    Env9_Buttom.grid(row=10, column=3)

def open_RVC():
    top_rvc = Toplevel()
    top_rvc.title("RVC Windows Environment ")
    
    Label_Links = Label(top_rvc, text="Links", pady=30, padx=80)
    Label_Links.grid(row=0,column=1)
    
    Label_Apps = Label(top_rvc, text="Applications", pady=30, padx=80)
    Label_Apps.grid(row=0,column=2)

    Label_Env = Label(top_rvc, text="Enviroment", pady=30, padx=80)
    Label_Env.grid(row=0,column=3)

    Link0_Buttom = Button(top_rvc, text="MFQ2", pady=30, padx= 80, command=action_0)
    Link1_Buttom = Button(top_rvc, text="Q Incidents", pady=30, padx= 80, command=action_1)
    Link2_Buttom = Button(top_rvc, text="Q Events", pady=30, padx= 80, command=action_2)
    Link3_Buttom = Button(top_rvc, text="Failure Analysis", pady=30, padx= 80, command=action_1)
    Link4_Buttom = Button(top_rvc, text="CLiberacion", pady=30, padx= 80, command=action_1)
    Link5_Buttom = Button(top_rvc, text="PQA", pady=30, padx= 80, command=action_1)
    Link6_Buttom = Button(top_rvc, text="Prod Validation", pady=30, padx= 80, command=action_1)
    Link7_Buttom = Button(top_rvc, text="Concesion", pady=30, padx= 80, command=action_1)
    Link8_Buttom = Button(top_rvc, text="QI", pady=30, padx= 80, command=action_1)
    Link9_Buttom = Button(top_rvc, text="PQI", pady=30, padx= 80, command=action_1)

    App0_Buttom = Button(top_rvc, text="BTDB", pady=30, padx= 80, command=action_1)
    App1_Buttom = Button(top_rvc, text="SAP", pady=30, padx= 80, command=action_1)
    App2_Buttom = Button(top_rvc, text="ECAM", pady=30, padx= 80, command=action_1)
    App3_Buttom = Button(top_rvc, text="Actividades", pady=30, padx= 80, command=action_1)
    App4_Buttom = Button(top_rvc, text="ProdEngWeb", pady=30, padx= 80, command=action_1)
    App5_Buttom = Button(top_rvc, text="MWS", pady=30, padx= 80, command=action_1)
    App6_Buttom = Button(top_rvc, text="Oisnet", pady=30, padx= 80, command=action_1)
    App7_Buttom = Button(top_rvc, text="App7", pady=30, padx= 80, command=action_1)
    App8_Buttom = Button(top_rvc, text="App8", pady=30, padx= 80, command=action_1)
    App9_Buttom = Button(top_rvc, text="App9", pady=30, padx= 80, command=action_1)

    Env0_Buttom = Button(top_rvc, text="PQA_QAM", pady=30, padx= 80, command=action_1)
    Env1_Buttom = Button(top_rvc, text="QISupport", pady=30, padx= 80, command=action_1)
    Env2_Buttom = Button(top_rvc, text="MiniPSS", pady=30, padx= 80, command=action_1)
    Env3_Buttom = Button(top_rvc, text="DLR", pady=30, padx= 80, command=action_1)
    Env4_Buttom = Button(top_rvc, text="CheckList", pady=30, padx= 80, command=action_1)
    Env5_Buttom = Button(top_rvc, text="ReportesAnalisis", pady=30, padx= 80, command=action_1)
    Env6_Buttom = Button(top_rvc, text="AnalisisWeb", pady=30, padx= 80, command=action_1)
    Env7_Buttom = Button(top_rvc, text="Mantenimientos", pady=30, padx= 80, command=action_1)
    Env8_Buttom = Button(top_rvc, text="App9", pady=30, padx= 80, command=action_1)
    Env9_Buttom = Button(top_rvc, text="App9", pady=30, padx= 80, command=action_1)

    # align buttoms in columns and rows according layout
    Link0_Buttom.grid(row=1,column=1)
    Link1_Buttom.grid(row=2,column=1)
    Link2_Buttom.grid(row=3,column=1)
    Link3_Buttom.grid(row=4,column=1)
    Link4_Buttom.grid(row=5,column=1)
    Link5_Buttom.grid(row=6,column=1)
    Link6_Buttom.grid(row=7,column=1)
    Link7_Buttom.grid(row=8,column=1)
    Link8_Buttom.grid(row=9,column=1)
    Link9_Buttom.grid(row=10,column=1)

    App0_Buttom.grid(row=1, column=2)
    App1_Buttom.grid(row=2, column=2)
    App2_Buttom.grid(row=3, column=2)
    App3_Buttom.grid(row=4, column=2)
    App4_Buttom.grid(row=5, column=2)
    App5_Buttom.grid(row=6, column=2)
    App6_Buttom.grid(row=7, column=2)
    App7_Buttom.grid(row=8, column=2)
    App8_Buttom.grid(row=9, column=2)
    App9_Buttom.grid(row=10, column=2)

    Env0_Buttom.grid(row=1, column=3)
    Env1_Buttom.grid(row=2, column=3)
    Env2_Buttom.grid(row=3, column=3)
    Env3_Buttom.grid(row=4, column=3)
    Env4_Buttom.grid(row=5, column=3)
    Env5_Buttom.grid(row=6, column=3)
    Env6_Buttom.grid(row=7, column=3)
    Env7_Buttom.grid(row=8, column=3)
    Env8_Buttom.grid(row=9, column=3)
    Env9_Buttom.grid(row=10, column=3)

def open_PP():
    top_pp = Toplevel()
    top_pp.title("PP Windows Environment  ")

    Label_Links = Label(top_pp, text="Links", pady=30, padx=80)
    Label_Links.grid(row=0,column=1)
    
    Label_Apps = Label(top_pp, text="Applications", pady=30, padx=80)
    Label_Apps.grid(row=0,column=2)

    Label_Env = Label(top_pp, text="Enviroment", pady=30, padx=80)
    Label_Env.grid(row=0,column=3)

    Link0_Buttom = Button(top_pp, text="MFQ2", pady=30, padx= 80, command=action_0)
    Link1_Buttom = Button(top_pp, text="Q Incidents", pady=30, padx= 80, command=action_1)
    Link2_Buttom = Button(top_pp, text="Q Events", pady=30, padx= 80, command=action_2)
    Link3_Buttom = Button(top_pp, text="Failure Analysis", pady=30, padx= 80, command=action_1)
    Link4_Buttom = Button(top_pp, text="CLiberacion", pady=30, padx= 80, command=action_1)
    Link5_Buttom = Button(top_pp, text="PQA", pady=30, padx= 80, command=action_1)
    Link6_Buttom = Button(top_pp, text="Prod Validation", pady=30, padx= 80, command=action_1)
    Link7_Buttom = Button(top_pp, text="Concesion", pady=30, padx= 80, command=action_1)
    Link8_Buttom = Button(top_pp, text="QI", pady=30, padx= 80, command=action_1)
    Link9_Buttom = Button(top_pp, text="PQI", pady=30, padx= 80, command=action_1)

    App0_Buttom = Button(top_pp, text="BTDB", pady=30, padx= 80, command=action_1)
    App1_Buttom = Button(top_pp, text="SAP", pady=30, padx= 80, command=action_1)
    App2_Buttom = Button(top_pp, text="ECAM", pady=30, padx= 80, command=action_1)
    App3_Buttom = Button(top_pp, text="Actividades", pady=30, padx= 80, command=action_1)
    App4_Buttom = Button(top_pp, text="ProdEngWeb", pady=30, padx= 80, command=action_1)
    App5_Buttom = Button(top_pp, text="MWS", pady=30, padx= 80, command=action_1)
    App6_Buttom = Button(top_pp, text="Oisnet", pady=30, padx= 80, command=action_1)
    App7_Buttom = Button(top_pp, text="App7", pady=30, padx= 80, command=action_1)
    App8_Buttom = Button(top_pp, text="App8", pady=30, padx= 80, command=action_1)
    App9_Buttom = Button(top_pp, text="App9", pady=30, padx= 80, command=action_1)

    Env0_Buttom = Button(top_pp, text="PQA_QAM", pady=30, padx= 80, command=action_1)
    Env1_Buttom = Button(top_pp, text="QISupport", pady=30, padx= 80, command=action_1)
    Env2_Buttom = Button(top_pp, text="MiniPSS", pady=30, padx= 80, command=action_1)
    Env3_Buttom = Button(top_pp, text="DLR", pady=30, padx= 80, command=action_1)
    Env4_Buttom = Button(top_pp, text="CheckList", pady=30, padx= 80, command=action_1)
    Env5_Buttom = Button(top_pp, text="ReportesAnalisis", pady=30, padx= 80, command=action_1)
    Env6_Buttom = Button(top_pp, text="AnalisisWeb", pady=30, padx= 80, command=action_1)
    Env7_Buttom = Button(top_pp, text="Mantenimientos", pady=30, padx= 80, command=action_1)
    Env8_Buttom = Button(top_pp, text="App9", pady=30, padx= 80, command=action_1)
    Env9_Buttom = Button(top_pp, text="App9", pady=30, padx= 80, command=action_1)


    # align buttoms in columns and rows according layout
    Link0_Buttom.grid(row=1,column=1)
    Link1_Buttom.grid(row=2,column=1)
    Link2_Buttom.grid(row=3,column=1)
    Link3_Buttom.grid(row=4,column=1)
    Link4_Buttom.grid(row=5,column=1)
    Link5_Buttom.grid(row=6,column=1)
    Link6_Buttom.grid(row=7,column=1)
    Link7_Buttom.grid(row=8,column=1)
    Link8_Buttom.grid(row=9,column=1)
    Link9_Buttom.grid(row=10,column=1)

    App0_Buttom.grid(row=1, column=2)
    App1_Buttom.grid(row=2, column=2)
    App2_Buttom.grid(row=3, column=2)
    App3_Buttom.grid(row=4, column=2)
    App4_Buttom.grid(row=5, column=2)
    App5_Buttom.grid(row=6, column=2)
    App6_Buttom.grid(row=7, column=2)
    App7_Buttom.grid(row=8, column=2)
    App8_Buttom.grid(row=9, column=2)
    App9_Buttom.grid(row=10, column=2)

    Env0_Buttom.grid(row=1, column=3)
    Env1_Buttom.grid(row=2, column=3)
    Env2_Buttom.grid(row=3, column=3)
    Env3_Buttom.grid(row=4, column=3)
    Env4_Buttom.grid(row=5, column=3)
    Env5_Buttom.grid(row=6, column=3)
    Env6_Buttom.grid(row=7, column=3)
    Env7_Buttom.grid(row=8, column=3)
    Env8_Buttom.grid(row=9, column=3)
    Env9_Buttom.grid(row=10, column=3)

btn_mrr = Button(root, text="MRR4", command=open_MRR)
btn_rvc = Button(root, text="RVC", command= open_RVC)
btn_pp  = Button(root, text="PP", command=  open_PP )

btn_mrr.grid(row=1,column=1, padx=40, pady=40)
btn_rvc.grid(row=1,column=2, padx=40, pady=40)
btn_pp.grid(row= 1,column=3, padx=40, pady=40)

root.mainloop()
